### ISSUE TITLE
Number of concurrent users

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#11]
The CAP is currently advertised to support 50 concurrent users. However, that is on Wi-Fi only i.e. layer 2. The way it is tested, is that 50 clients are connected to the AP, and a classroom management software is used to test the performance of the Wi-Fi. The test does NOT involve the webserver.

As the processor is a single core Atom processor, it is unlikely that the CAP supports 50 concurrent users accessing RACHEL.

It would be great to run a test, though that is a lot of work.

**Comment by j-schwartz** [comment]
What would you recommend to do the actual test.  I can get 50 people with laptops or mobile devices, I guess I'm just not sure how to turn that into a meaningful set of data to prove out a point.  

With RACHEL-Pi a Southwest airlines flight attendant let me announce a test on the plane and I got anecdotal feedback.  I'd like to do something that gets actual data if I do something similarly again.

**Comment by edresor** [comment]
I am also worried about the number of simultaneous users on an actual web server with Kiwix-Serve running in parallel with the webserver and with some web server clients using Flash for the older PhET or GCF Learn Free videos.  I think we should include Flash because we may get local content that uses Flash even if all of this content is upgraded to HTML 5.

Some of the test users should be located where the RF path is marginal, but usable, i.e. around a corner or through a wall.

If we have enough capacity to support 20 WiFi users running different stuff on different equipment, that would be enough capacity for me, especially if we could increase web server capacity by adding a WiFi router and moving the WiFi users to that access point.

Generally users in Africa are patient as long as they can "see" that the server has not hung up. If one or more clients are getting service, the others will be willing to wait before holding down the shutdown button to shut down and then restart the system.

Another, more difficult upgrade is increasing the RAM by replacing the 2-GByte module with a 4-Gbyte module.

**Many of you may want to skip some or all of the following sections.**

**How do the WiFi users affect the capacity of the CPU to support servers?**

I would love to see a block diagram of the circuit for the whole CAP to try to figure out how much of the WiFi processing is done by the Atom CPU. The lower the WiFi load on the CPU, the better.  I am concerned particularly the processing related to MIMO and changing speed and forward error correction depending upon the RF link and interference.

If the CPU is doing some of the WiFi work, the following settings might affect its capacity.  I think adequate capacity on 2.4 GHz should be good enough.  802.11 b/g would remove the MIMO load, but slowing down the link might reduce the web server capacity.

**The relevant WiFi choices are listed below.**
**Wireless Mode         Bandwidth Channel**
802.11 b/g mixed 2.4 GHz	20 MHz only
802.11 g/n mixed 2.4 GHz	20 MHz or 40/20 MHz.
802.11 b/g/n mixed 2.4 GHz	20 MHz or 40/20 MHz.

**Wireless Channel:**  Auto or a specified channel.

I am willing to reduce load on the CPU with the following settings:
**Anti-Interference Mode:**  Off
**Security Mode:**  Open
Some people might disagree on security because a link with no security can cause problems on some websites on the Internet.


**Educational Needs Driving the Need for Multiple Users of these Servers**

KA-Lite and Kiwix-Server are our priorities In East Africa because we are working extremely hard to get more student access to devices so they begin to have some "learner-centered" education, which everyone, including the key government agencies, agrees they need. To deliver "learner-centered" education we need students to be able to have individual accounts on KA-Lite which are not corrupted by power failures or human initiated shutdowns. We also need to be able to have each student or several students working on what she, he, or they need, including doing research with Kiwix-serve and resources in RACHEL or even watching TED talks from a ZIM file archive using locally added resources.

**Is it worth the risk of upgrading to a dual core Atom CPU?**

If we run into capacity limits with our testing, how risky would it be to upgrade the RAM and/or the CPU in the next production run?

I am not worried about increasing power consumption because we have a great battery for what we really need: riding through outages in the middle of a one or two hour work session and shutting down after closing all open databases to which critical data is being written.

I wondered if we went to a dual core Atom chip in the same family would it give us more capacity and would we have to start over with testing new drivers and a new configuration of Ubuntu?

Note: According to the **Intel® Atom™ Processor E3800 Product Family Datasheet, January 2015 Revision 3.6,** our chip, the Intel® Atom™ Processor E3815, is the only single core chip in the E3800 family. The two intermediate dual core models, the E3826 and the E3827, increase the power consumption from 5 watts to 7 and 8 watts respectively.

Of course, the overhead to manage two cores could hurt rather than help our performance.

The E3827 for an increase of $10, from $31 to $41, in the "Recommended Customer Price" increases L2 cache from 512 Kbytes to 1 MByte, the speed from 1.46 to 1.75 GHz, the DDR speed from 1033 to 1333 DDR (MT/s) and the maximum RAM capacity from 4 GB to 8GB: however it is not clear that all 8 GB could be in one SIMM.

The E3827 requires more expensive 1333 DDR memory so that will add to the cost and probably the power consumption.  The E3826 1.46 GHz dual core with 1 MByte of L2 cache might be better to save on RAM cost and save also about $4 on the cost of the CPU.

**Comment by bnordha** [comment]
It is pretty easy to upgrade the RAM from 2Gb to 4GB (which is the maximum for this chipset). It takes about 10minutes to do so. It requires some disassembly, the RAM simply snaps in.

 

The CPU is NOT upgradable. It is soldered to the motherboard. 

 

There is a block diagram that Intel shares under NDA. 

 

Bernd

**Comment by spatiald** [comment]
I believe this issue will resolve itself with v2.   This is a v1 issue only without any likely solution before v2 rolls out.  Closing.
