### ISSUE TITLE
Weaved Install Options

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#40]
Option 5 is not downloading weaved install files

![image](https://cloud.githubusercontent.com/assets/9270388/12157259/5b64afec-b485-11e5-9b41-370cdc7a50d7.png)

Option 4 for weaved (defualt install) never asks for a weaved user name or device name?  I can register through the online portal, but that offers two HTTP services an no way to delineate which is which.

**Comment by spatiald** [comment]
That is probably caused by the addition of the default installer you built
that I tried to incorporate.

I'll look at this tonight/tomorrow.



On Jan 6, 2016, at 17:55, Jeremy Schwartz <notifications@github.com> wrote:

Option 5 is not downloading weaved install files

[image: image]
<https://cloud.githubusercontent.com/assets/9270388/12157259/5b64afec-b485-11e5-9b41-370cdc7a50d7.png>

Option 4 for weaved (defualt install) never asks for a weaved user name or
device name? I can register through the online portal, but that offers two
HTTP services an no way to delineate which is which.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/40>.

**Comment by hackersforcharity** [comment]
Sorry, I am not saying that are the source of the issue. Rather, it's my
implementation. :)

On Jan 6, 2016, at 23:11, Sam Kinch <notifications@github.com> wrote:

That is probably caused by the addition of the default installer you built
that I tried to incorporate.

I'll look at this tonight/tomorrow.



On Jan 6, 2016, at 17:55, Jeremy Schwartz <notifications@github.com> wrote:

Option 5 is not downloading weaved install files

[image: image]
<
https://cloud.githubusercontent.com/assets/9270388/12157259/5b64afec-b485-11e5-9b41-370cdc7a50d7.png
>

Option 4 for weaved (defualt install) never asks for a weaved user name or
device name? I can register through the online portal, but that offers two
HTTP services an no way to delineate which is which.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/40>.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/40#issuecomment-169543422>
.

**Comment by spatiald** [comment]
The default installer they provided doesn't register - it just adds default services that can be registered later.  It's a nice option for mass producing CAPs that you can tailor later.  Running option 4 for weaved service will prompt for user/pass and register at that time.

Reopen, if necessary.
