### ISSUE TITLE
1.2.16 USB - KA-Lite exercises

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#41]
@spatiald is it hard to create the USB image?  I don't think the current one includes KA-lite exercises or subtitles.  I'm 99% sure the last one had at least exercises.  Hate asking you if this is something reasonable I can do (create a new USB image)

**Comment by spatiald** [comment]
@j-schwartz We spoke on the phone about this but wanted to summarize here.  The USB image creation process is documented [here](http://rachel.golearn.us/wiki/mdwiki.html#!cap-usb-creation.md).  I will be adding more details in the next couple weeks.

**Comment by spatiald** [comment]
@j-schwartz Well, I had good intentions of locating the assessmentitems.sqlite file on the external hard drive.  

@rachelproject/rachel I will provide the background and fix below.  Sorry about this mess...

## BACKGROUND
The assessmentitems.sqlite (assessment items) are downloaded and installed as part of installing the ka-lite bundle (which we do).  It installs the file to a system folder at:  ```/usr/share/kalite/assessment/khan/assessmentitems.sqlite```

I had changed the location in the settings file:  ```/root/.kalite/settings.py``` to point to:  ```/media/RACHEL/kacontent``` because I thought it was much larger than it really is and I try to keep our larger content on the hard drive.  However, the installer still installs the file to the system folder mentioned above; since I didn't copy the assessment file to the hard drive, it would not load them. 

## FIX
Remove the redirection of the assessment file to the hard drive.  I built the repair into the configure script below.

Run the rachel configure script:
```bash
wget https://raw.githubusercontent.com/rachelproject/rachelplus/master/cap-rachel-configure.sh \
-O /root/cap-rachel-configure.sh; bash /root/cap-rachel-configure.sh
```
Choose Option 8, then Option 7 "Repair-KA-Lite"

I will put out an updated USB image soonest.
