### ISSUE TITLE
cap-rachel-configure.sh Paths have changed

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#42]
It looks like some there are some minor issues with  cap-rachel-configure.sh script 

1) The cap-rachel-configure.sh doesn't appear to go through all the iterations.
The log file reports 
sed: can't read /root/rachel-scripts.sh: No such file or directory

2) Some of the paths have changed.
For example the kiwix installation files appeared to have moved to http://rachelfriends.org/downloads/public_ftp/z-holding/ whereas the script expects them to be at http://rachelfriends.org/z-holding/

**Comment by spatiald** [comment]
Hi Bernd,
Was that with a new cap install?  Can you attach the full log?

On Jan 18, 2016, at 20:52, bnordha <notifications@github.com> wrote:

It looks like some of the paths have changed which cause the
cap-rachel-configuresh script to break

1) The log file reports
sed: can't read /root/rachel-scriptssh: No such file or directory

The cap-rachel-configuresh doesn't appear to go through all the iterations

For example the kiwix installation files appeared to have moved to
http://rachelfriendsorg/downloads/public_ftp/z-holding/

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/42>.

**Comment by bnordha** [comment]
yes, it was. 

[rachel-install.tmp.txt](https://github.com/rachelproject/rachelplus/files/95253/rachel-install.tmp.txt)

**Comment by spatiald** [comment]
Try the beta version (added fix...the next script wouldn't run because sed
would add the install script 2 line to a file that didn't exist.  The fix
creates the file with basic content so the lines are added correctly during
script execution.

See commit for more info:
https://github.com/rachelproject/rachelplus/commit/84c67b57b4ff2db97f4f01074d6328199e33f5aa

wget https://raw.githubusercontent.com/rachelproject/rachelplus/beta/cap-rachel-configure.sh
\
-O /root/cap-rachel-configure.sh; bash /root/cap-rachel-configure.sh

**Comment by spatiald** [comment]
Fixed; reopen, if necessary.
