### ISSUE TITLE
I am unable to access :8080 to configure Network

### ISSUE THREAD

**Issue by click2tman** [rachelproject/rachelplus#48]
I am unable to access :8080 to configure Network and when I visit 192.168.88.1, I see the following
"It works!
This is the default web page for this server.
The web server software is running but no content has been added, yet."
Accessing my.content does not produce anything. In short its not working right for me. I tried running the configure script ./cap-rachel-configure.sh -r to repair. Here is my output

root@WRTD-303N-Server:~# ./cap-rachel-configure.sh -r

RACHEL CAP Configuration Script - Version 20160210.0552
[+] Started:  Thu Mar  3 14:30:27 EST 2016
[+] Log directory:  /var/log/RACHEL
[+] Temporary file directory:  /root/cap-rachel-install.tmp

[?] Do you want to run in ONLINE or OFFLINE mode?
1) ONLINE
2) OFFLINE
#? 1

[+] Script set for 'ONLINE' mode.

[+] Internet connection confirmed...continuing install.
[+] Ubuntu "12.04" i686 Detected.

[*] Checking for pre-existing RACHEL content shell.

[*] /media/RACHEL/rachel exists; updating RACHEL content shell from GitHub.
Already up-to-date.
[*] Restarting lighttpd web server to activate changes.
lighttpd: no process found
[+] Done.

[*] Creating /root/batteryWatcher.sh
This script will monitor the battery charge level and shutdown this device with less than 3% battery charge.
[*] Checking for and killing previously run battery monitoring scripts
[*] Logging shutdowns to /var/log/RACHEL/shutdown.log
[+] Script started...monitoring battery.

[*] Updating /root/rachel-scripts.sh
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server

[*] Setting up Kiwix to start at boot...
[+] Done.
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server

[*] Setting up KA Lite to start at boot...
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
[+] Done.
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server
sudo: unable to resolve host WRTD-303N-Server

[*] Added check to disable the reset button
[+] Done.

[+] Rachel script update completed.

[*] Adding the local content module.
receiving incremental file list

sent 33 bytes  received 146 bytes  119.33 bytes/sec
total size is 37852430  speedup is 211466.09
[+] Done.

[+] Repair complete.

[+] Log file saved to: /var/log/RACHEL/cap-rachel-configure-Mar-03-2016-1430EST.log

[?] Were there errors?
Enter 'y' to exit without cleaning up temporary folders/files. (y/N) n

[*] Cleaning up install scripts.
[+] Done.

**Comment by j-schwartz** [comment]
After selecting online you should be presented with options, including to download content.

Why were you running these scripts?  Trying to diagnose how you got to a point where there wasn't content installed on your device?  I'm not sure when a device would lose the intel dashboard

**Comment by spatiald** [comment]
@click2tman Jeremy is correct...you have an issue that needs to be fixed by using the RACHEL Recovery USB.  Please download by following these instructions:
[](http://rachel.golearn.us/wiki/mdwiki.html#!cap-usb-recovery.md)

Follow the instructions here to burn to a USB:
[](http://192.168.100.16/wiki/mdwiki.html#!cap-usb-creation.md)

**Comment by hackersforcharity** [comment]
@click2tman The issue didn't show correctly. Please go here for the links:
https://github.com/rachelproject/rachelplus/issues/48#issuecomment-192804626

Sam

On Mar 5, 2016, at 23:47, Sam Kinch <notifications@github.com> wrote:

@click2tman <https://github.com/click2tman> Jeremy is correct...you have an
issue that needs to be fixed by using the RACHEL Recovery USB. Please
download by following these instructions:
<http://rachel.golearn.us/wiki/mdwiki.html#!cap-usb-recovery.md>

Follow the instructions here to burn to a USB:
<http://192.168.100.16/wiki/mdwiki.html#!cap-usb-creation.md>

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/48#issuecomment-192804626>
.

**Comment by spatiald** [comment]
Reopen if problem is unsolved.
