### ISSUE TITLE
Intel CAP 101

### ISSUE THREAD

**Issue by tertiusstrydom** [rachelproject/rachelplus#49]
Hi,

We just received a demo Intel CAP unit from Intel but we're struggling to find documentation on customizing the interface. Things like the root password, etc.
We tried root and 123lkj which didn't work. Only combo that works for SSH login is Ken and 123lkj

Can anyone please point us in the right direction.

Thanks

**Comment by hackersforcharity** [comment]
Our CAPs are heavily modified for RACHEL.  We reverse engineered much of
what Intel (and the manufacturer, Gemtek) were doing.

We documented some of our adventures here:  http://rachel.golearn.us/wiki

It should answer many of your questions.

On Mar 17, 2016, at 02:49, tertiusstrydom <notifications@github.com> wrote:

Hi,

We just received a demo Intel CAP unit from Intel but we're struggling to
find documentation on customizing the interface. Things like the root
password, etc.
Can anyone please point us in the right direction.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/49>

**Comment by tertiusstrydom** [comment]
Thanks. I'm keen to try the RACHEL image on the device but will have to revert back to original Intel image before returning the unit. Will this be possible?

**Comment by hackersforcharity** [comment]
Sure, just use Intels interface to install the Intel firmware back.

On Mar 17, 2016, at 03:45, tertiusstrydom <notifications@github.com> wrote:

Thanks. I'm keen to try the RACHEL image on the device but will have to
revert back to original Intel image before returning the unit. Will this be
possible?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/49#issuecomment-197742491>

**Comment by jjmuriel** [comment]
Hi,


Yow know where can I get the original Intel firmware?


Thank you

**Comment by tertiusstrydom** [comment]
I've only been able to get a generic image from the manufacturer. Even the Intel guys pointed me to this FTP site to get the generic image.

 ftp://ContentAccessPoint:FWRelease@ftp.gemteks.com

**Comment by bnordha** [comment]
If you want to completely restore a unit, do a USB Recovery. You can find the files and the instructions on the same FTP site under ftp://ftp.gemteks.com/USBRecovery/

**Comment by tertiusstrydom** [comment]
That works but as stated above the Gemteks site only have generic, non-branded images. It's not the original Intel branded image that the unit ships with.

**Comment by bnordha** [comment]
Intel only had branding on earlier versions of the firmware. The more recent ones have removed the branding. 

Thus, I suspect that you received on old version. Do know what the version of the firmware is? Also, if I may ask, who at Intel did you get the unit from? I used to work at Intel until last year.

**Comment by tertiusstrydom** [comment]
Got the unit from Ryan Macquet at Intel South Africa.

Anyone know of developers that can customize software and functionality for these units? Also need advice on how to setup cloud repository for learning material.

Thanks

**Comment by bnordha** [comment]
Ryan joined after I left. In general, Intel doesn't provide much developer support for the CAP, but you can check with Intel SA.

**Comment by spatiald** [comment]
Reopen if issue is still valid.

**Comment by jjmuriel** [comment]
Thanks a lot!!
