### ISSUE TITLE
Add stemming module for PHP

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#51]
Some modules now come with their own self-contained search implementation. This requires a new PHP module. I install as follows:
```
apt-get install php-pear
apt-get install php5-dev
yes '' | pecl install -f stem
```
Then you have to add the line:
```
extension=stem.so
```
To the `/etc/php5/cli/php.ini` and `/etc/php5/apache2/php.ini` (on the pi, at least).

**Comment by spatiald** [comment]
I don't install php-pear by default.  I can easily add/install that in future builds.  The problem I encounter is running "yes '' | pecl install -f stem".  It fails with an executable error.  Had to run "chmod +x /usr/bin/yes" before it would continue.  Then it failed on a php error (didn't copy the error in time before I screwed things up by trying to upgrade)...I'll have to recover my CAP but will retest and provide some more feedback/error reports.

**Comment by needlestack** [comment]
Strange... maybe there's another way to install the module? The releases are here:

  https://pecl.php.net/package/stem

**Comment by hackersforcharity** [comment]
Yeah, saw that. I just received my latest batch of CAPs. Since I have the
demo back up, after bringing it down yesterday, I'll check on this again.

On Apr 21, 2016, at 02:54, Jonathan Field <notifications@github.com> wrote:

Strange... maybe there's another way to install the module? The releases
are here:

https://pecl.php.net/package/stem

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/51#issuecomment-212771559>

**Comment by spatiald** [comment]
Added to the latest configure script and v8 of the RACHEL Recovery USB.
