### ISSUE TITLE
Consider partition resizing

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#55]
I think after a year of using these, we can safely resize partitions even futher:

We're currently at 20G for "preloaded" / 100G for "uploaded" / 340G for "RACHEL"

I'd suggest a new 3G / 17G / 440G mix

Thoughts?

**Comment by hackersforcharity** [comment]
That will require some work on the USB recovery to make it "universal" but
not impossible.

I agree with the premises for the sizes.


On May 23, 2016, at 20:30, Jeremy Schwartz <notifications@github.com> wrote:

I think after a year of using these, we can safely resize partitions even
futher:

We're currently at 20G for "preloaded" / 100G for "uploaded" / 340G for
"RACHEL"

I'd suggest a new 3G / 17G / 440G mix

Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/55>

**Comment by j-schwartz** [comment]
Ah, good point. Maybe we wait till Gen2 of the CAP and see if it has some
identifying physical difference so we can tell people only use this USB
with Gen2?

**Comment by edresor** [comment]
I agree strongly on the need for more space in the RACHEL partition.  With the latest delay in the CAP 2.0 and the next order of 200 CAP 1.0s on the way, I would suggest going forward now or as soon as practical so most of the next 200 can go out with the larger RACHEL partition.
I am in over my head here, but maybe we could have a Method 0 if necessary that would leave the partitions alone.  Alternatively, we could put rewriting the partitions in an optional script, or a separate script to run as needed with a choice of partition layouts.

**Comment by needlestack** [comment]
2016.10.12 takes care of this - new sizes:

/media/preloaded - 3GB
/media/uploaded - 17GB
/media/RACHEL - 439GB
