### ISSUE TITLE
bad db for some modules

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#58]
When we made the name format change to start with the language code, it broke the links in the db for the following modules:

```
en-hesperian_health/search/hesperian_health.db
en-infonet/search/infonet.db
en-law_library/search/law_library.db
en-medline_plus/search/medline_plus.db
en-oya/search/oya.db
en-practical_action/search/practical_action.db
```

I have updated these modules on dev so an rsync will fix it. Alternately, you can fix it with the following command:

`sqlite3 [modname]/search/[dbname].db "update pages set url = 'en-'||url"`

Sorry for the rigmarole related to this change. Will be more careful in the future.

**Comment by spatiald** [comment]
Rsync is the prob the safest and easiest. Thanks for the info!

On May 26, 2016, at 03:52, Jonathan Field <notifications@github.com> wrote:

When we made the name format change to start with the language code, it
broke the links in the db for the following modules:

en-hesperian_health/search/hesperian_health.db
en-infonet/search/infonet.db
en-law_library/search/law_library.db
en-medline_plus/search/medline_plus.db
en-oya/search/oya.db
en-practical_action/search/practical_action.db
es-wikihow/search/wikihow-es.db

I have updated these modules on dev so an rsync will fix it. Alternately,
you can fix it with the following command:

sqlite3 [modname]/search/[dbname].db "update pages set url = 'en-'||url"

But be sure to put "es-" if you're updating es-wikihow.

Sorry for the rigmarole related to this change. Will be more careful in the
future.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/58>

**Comment by spatiald** [comment]
Believe sorted...reopen if necessary.
