### ISSUE TITLE
Slow (4+ hours) kalite upgrade

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#59]
When upgrading kalite on the plus it can take upwards of 4 hours before kalite is available:

![unnamed](https://cloud.githubusercontent.com/assets/5177260/15582883/82ef3944-2373-11e6-8c32-ba58638f8de9.png)

Jonathan said:

I'm pretty sure that this is the same as running the videoscan. It's fine to do it, but it should work to skip the "manage" script and just use the Db that comes with the kalite Rachel module.

In any case, we have to focus in on kalite issues, try to stabilize on a good version, and then have a testing checklist before we upgrade to newer versions.

Sam said:

Agree with all...I think my only concern with using the supplied DB is that we are not settled on a location for the videos to rsync with.  I know you provide them with the module but we can not do that with multi-version CAPs, unfortunately.

**Comment by needlestack** [comment]
I think it's possible to work this out for the multi-lingual CAPs. Luckily for us kalite uses a different db file for each language, so for a multi-lingual install we can just copy all those to the database directory (one from each module).

I believe the videos can likewise all be pulled into the same directory as they don't use the same IDs. This should make it so that you can select any language through the kalite admin interface without having to do a videoscan. But I admit I haven't tested that.

**Comment by spatiald** [comment]
Already...I just experienced Jeremy's 5 hour kalite videosync when running 0.16.5.  It happened on one of the Chinese imaged  hard drives.  I didn't clone it like I normally do.  Not sure what is going on there...

**Comment by needlestack** [comment]
Interesting. I am curious what you mean by multi-kalite install? Do you mean multiple languages on one device? What problems were you seeing?

**Comment by spatiald** [comment]
https://ka-lite.readthedocs.io/en/latest/usermanual/userman_admin.html#registering-your-device-with-the-hub

KA Lite allows for data syncing for multi-client installs that sync to an
administrative hub.

**Comment by spatiald** [comment]
This is a KA Lite issue that I don't think they will resolve soon.  We can significantly reduce first-time start time by pre-building and deploying the KA Lite database. The only thing that this affects is multi-site installs where the org needs unique IDs for each site. 

The latest v8 USB does NOT remove the device ID no crypto keys. This way, first-run of KA Lite does not take ~5 hours.  The only effect of doing this is that we will have to customize multi-site installs with some individual attention. Since we rarely do this, this decision should have little affect.
