### ISSUE TITLE
Standardized RACHEL banner across different modules - ie Home "button"

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#6]
After captive portal, clicking a link, makes it hard to get back to RACHEL home page.

**Comment by spatiald** [comment]
Any thoughts on how to update this?  Not sure if html5 provides a method similar to frames for doing so.  Only other option I can think of is opening a new tab for each module that the user goes to.  Right now, I believe that is a little inconsistent.  Some modules open in the same tab and some modules open in new tabs.

**Comment by bnordha** [comment]
Good point, I think kiwix and Ka-lite should open a new tab, but regular
modules should not.

For those, I like the idea of a standard banner.

**Comment by spatiald** [comment]
Still an issue...

@needlestack Any thoughts on how we might incorporate a "Home" button across all content?  Or should we just open up new content in a new window?  

One thought...we might provide a way for users to set their home page to the RACHEL main page.  Could we add a link to "Set RACHEL as your home page" from the "local content" module?

**Comment by needlestack** [comment]
Yeah, I've thought about this a lot though I don't have a solution. It would be nice to keep a banner at the top, but it's not possible with kiwix and questionable with kalite. It could be forced with a frame, but then the address bar wouldn't change and so you couldn't copy/paste/bookmark links anymore, which I think is a problem.

Honestly, even opening in a new tab is not going to do much for novice users (who seem very confused by tabs if they're aware of them).

At this point I had just been assuming that people can find their way back. But I think what I'd like as policy is something like what bnorda suggested:

1. add a banner to everything we can [e.g. Great Books](http://dev.worldpossible.org/mods/ebooks-en/index.html)
2. open in a new tab anything we can't

We'd have to put some time into getting existing modules in line...

**Comment by needlestack** [comment]
Alright, after some more usage, thoughts, and reports, I'm making a call on this. Using a `<base target="content">` tag, I'm going to push all content to a new tab - but a single new tab (not a new one for every click). This should normalize user experience until we can come up with something better.

The `<base target="content">` tag will not override a target specified in the `<a href="" taget="">` tag, so I'll also clean those up on dev where they were pointing to `"_blank"` or whatever. Also, if you *need* something to open in the same window as the RACHEL index, you can specify `target="_self"`.

**Comment by hackersforcharity** [comment]
That seems reasonable...thanks Jonathan

On Jul 1, 2016, at 18:39, Jonathan Field <notifications@github.com> wrote:

Alright, after some more usage, thoughts, and reports, I'm making a call on
this. Using a <base target="content"> tag, I'm going to push all content to
a new tab - but a single new tab (not a new one for every click). This
should normalize user experience until we can come up with something better.

The <base target="content"> tag will not override a target specified in the <a
href="" taget=""> tag, so I'll also clean those up on dev where they were
pointing to "_blank" or whatever. Also, if you *need* something to open in
the same window as the RACHEL index, you can specify target="_self".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/6#issuecomment-230062198>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGPnvM9Y7cMp_tQmd7j0YZ1EJ9fCmoXBks5qRZcbgaJpZM4FOk6j>
.
