### ISSUE TITLE
Weaved Script Removes Port 80

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#61]
Any reason we're dropping port 80 from Weaved?  I've found it very valuable to troubleshoot content remotely (at least see what's on the main page and access the stats portion of things)

**Comment by hackersforcharity** [comment]
I assumed that you didn't want it after our last conversation about remot.it
... no worries, I can put it back.

On Jun 3, 2016, at 18:21, Jeremy Schwartz <notifications@github.com> wrote:

Any reason we're dropping port 80 from Weaved? I've found it very valuable
to troubleshoot content remotely (at least see what's on the main page and
access the stats portion of things)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/61>, or mute the thread
<https://github.com/notifications/unsubscribe/AGPnvD9_BF2JnnTPXxJtNjF3a2kFRjl4ks5qIKkAgaJpZM4It9HL>
.

**Comment by j-schwartz** [comment]
Ah, totally my bad, it's 8080 that I don't know that we need (or that I
don't use)

**Comment by spatiald** [comment]
Updated in latest createUSB and cap-rachel-configure scripts
