### ISSUE TITLE
Weaved install - missing valid session

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#65]
![image](https://cloud.githubusercontent.com/assets/9270388/19017452/954549be-87ee-11e6-8ee7-3499a99b4132.png)

Any thoughts on this one?

**Comment by needlestack** [comment]
Is this resolved in the latest USB?

**Comment by spatiald** [comment]
It should be resolved...Jeremy, please test and confirm the new Weaved
install process works for you.

**Comment by j-schwartz** [comment]
I'm losing a weaved_IntelCAP.tar now, tar: weaved_IntelCAP.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

![image](https://cloud.githubusercontent.com/assets/9270388/19370061/23905d58-915e-11e6-9867-4da21f8a82fb.png)

**Comment by spatiald** [comment]
Need more specifics.  I just finished testing off the latest configure
script (option 4) and it works good for me.
- what option are you running?
- connected to the internet (it's a requirement now with the latest changes)

Maybe it's all those wireless RACHEL access points you have running :)

**Comment by j-schwartz** [comment]
haha you mean these??
![capture](https://cloud.githubusercontent.com/assets/9270388/19402156/5057835a-9214-11e6-9a3d-6a7a3b7e4a89.PNG)

It has to be something sporadic like that.  Today, the network was fine.  15 of 16 devices were able to register (none of those same devices could last night).  The last hold out is giving me this: 
![image](https://cloud.githubusercontent.com/assets/9270388/19402168/6d8ae62e-9214-11e6-91b3-4635cc9d1127.png)

I'll let is sit for another day and see what happens.  It is now the only device on the network and still no dice.

**Comment by spatiald** [comment]
That looks like a DNS issue. You might check your external Gateway.
Check two things: one, set the external/upstream DNS server to either
8.8.4.4 or to the OpenDNS servers and, two, in sure that your external
gateway does not allow DNS servers to be overwritten by upstream devices.
You probably have one bad upstream DNS server that isn't resolving right
and causing issues like the time outs you are seeing.

On Oct 14, 2016, at 16:45, Jeremy Schwartz <notifications@github.com> wrote:

haha you mean these??
[image: capture]
<https://cloud.githubusercontent.com/assets/9270388/19402156/5057835a-9214-11e6-9a3d-6a7a3b7e4a89.PNG>

It has to be something sporadic like that. Today, the network was fine. 15
of 16 devices were able to register (none of those same devices could last
night). The last hold out is giving me this:
[image: image]
<https://cloud.githubusercontent.com/assets/9270388/19402168/6d8ae62e-9214-11e6-91b3-4635cc9d1127.png>

I'll let is sit for another day and see what happens. It is now the only
device on the network and still no dice.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/65#issuecomment-253914752>,
or mute the thread

**Comment by spatiald** [comment]
I am going to close this issue based on the transition from Weaved to remot3.it

Once we have a new install method, this issue may be moot.  If not, reopen.
