### ISSUE TITLE
KA Lite issue with language handler?

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#68]
### RACHEL Version Info
Hardware	i686
OS	Ubuntu precise (12.04.3 LTS)
RACHEL Installer	1.2.16_20160920.0242 *
KA Lite	0.16.9-0ubuntu2 *
Kiwix	*
Content Shell	 ✔ Up to date Current: v2.1.0

### Website in URL
`http://192.168.100.101:8008/api/i18n/set_default_language/?lang=en&returnUrl=/?`

### ERROR (only content showing on website when clicking KA Lite)
`{"error": "Can only handle default language changes through POST requests"}
`

**Comment by needlestack** [comment]
So this is usually happens if `api_views.py` didn't get replaced or the server wasn't restarted afterwards. (This message is the default behavior). Since the inclusion of that patch, kalite modules are now multi-lingual, meaning they set the kalite language depending on which module you click on the front page. If the most recent modules are used, they require the update to `api_views.py`.

**Comment by spatiald** [comment]
Looks the issue resolved when I reinstalled content shell.  Thanks!

**Comment by L-Amstutz** [comment]
How does one fix this on an active RACHEL Plus without Internet connectivity?  (HDD content was cloned)

**Comment by needlestack** [comment]
You would need to download [this file](https://raw.githubusercontent.com/rachelproject/rachelplus/master/scripts/KALITE-MULTILINGUAL-api_views.py) and save it on that RACHEL-Plus as `/usr/lib/python2.7/dist-packages/kalite/i18n/api_views.py`, and then run `kalite restart`. This can be done through ssh if you can physically get to the RACHEL with a laptop and that file. Let me know if you need more info...

**Comment by L-Amstutz** [comment]
Thanks!  I copied the file to the specified directory on the RACHEL and restarted KA=Lite and now the nagging language error is gone.  I’ll do that on my other RACHEL Plus where I used the latest Recovery_USB to move the KA-Lite database to the HDD.  Oh, I also found the HTML code for the RACHEL Home index and corrected the rachel-index.php file to correctly spell “Economics”. It is looking very good that I will have all three of these RACHELs ready to take to Liberia in a couple of weeks with the latest updates.
Leon

**Comment by needlestack** [comment]
Super! Glad to hear it worked out!

**Comment by andrewclark55** [comment]
I have the same error running Ka Lite but replacing the file as suggested removes the error and still leaves Ka Lite not working.

" KA Lite logo
Foundation for Learning Equality logo
KA Lite version 0.16.9 © 2017
Videos © 2015 Khan Academy (Creative Commons) // Exercises © 2015 Khan Academy
Creative Commons Attribution-NonCommercial-ShareAlike 3.0 United States License"

It is suggested that my version of Ka Lite is out of date but all attempts to upgrade it to 0.17 on the RPi are failing.  Specifically I have tried running the code at:-
http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#raspberry-pi-install

I need to get this fixed for a deployment soon in Malawi.  Can anyone offer help as to how to fix it?
Regards
Andrew

**Comment by j-schwartz** [comment]
@andrewclark55 I think this fix is probably specific to RACHEL-Plus.  I'm not sure we have the same features built out on RACHEL-Pi.  I'm not totally sure, but I thought this issue was related to changing languages of KA-Lite on a device, and we've never dug into multi-language KA-Lite installs on a Pi.  Just haven't had the time.

**Comment by andrewclark55** [comment]
Hi Jeremy

Thanks very much for responding.

If the fix was only for RACHEL–Plus we will need to dig further to find why it is failing on RACHEL Pi.

My problem is that I know nothing about how Ka Lite is put together or how to maintain it.  Hopefully someone on here can come to the rescue!

Regards
Andrew

**Comment by j-schwartz** [comment]
Yes, agreed.  You should post on the RACHELPi GitHub also though: https://github.com/rachelproject/rachelpiOS

**Comment by andrewclark55** [comment]
Jeremy

Just doing that now.

Regards
Andrew
