### ISSUE TITLE
kiwix startup duplicated in rachelStartup.sh

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#73]
Just noticed that `rachelStartup.sh` starts kiwix twice -- the first time it does it directly, then later again with `rachelKiwixStart.sh` -- which kills and restarts the daemon. We should probably just do it once using `rachelKiwixStart.sh`.

I was going to modify this myself, but it is inserted via sed in different parts of cap-rachel-configure, and didn't want to disrupt anything I didn't understand.

**Comment by spatiald** [comment]
Good catch - I'll review and push an update via the next USB release (sched
after the soon to be released KA Lite update).

On Dec 9, 2016, at 17:11, Jonathan Field <notifications@github.com> wrote:

Just noticed that rachelStartup.sh starts kiwix twice -- the first time it
does it directly, then later again with rachelKiwixStart.sh -- which kills
and restarts the daemon. We should probably just do it once using
rachelKiwixStart.sh.

I was going to modify this myself, but it is inserted via sed in different
parts of cap-rachel-configure, and didn't want to disrupt anything I didn't
understand.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/73>, or mute the thread

**Comment by spatiald** [comment]
Fixed in release v2.0.0
