### ISSUE TITLE
batteryWatcher.sh and bad batteries

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#75]
I have a unit with a bad battery (won't charge). The unit still runs fine, but batteryWatcher.sh is too aggressive and shuts it down. I am pretty sure this is fixed by changing the threshold for what is considered "charging" -- replacing the following line:

```if [[ $(cat /tmp/chargeStatus) -lt -200 ]]; then```

with:

```if [[ $(cat /tmp/chargeStatus) -lt -20 ]]; then```

Specifically, my dead battery always reports a charge status of 0 when plugged in. And my working unit reports the same when plugged in and completely charged. I have noticed an occasional charge status in the -5 range when the good unit is plugged in, but I think -20 is a safe cutoff to identify plugged in vs. not plugged in.

**Comment by spatiald** [comment]
Fairly extensive testing went into identifying that number. When charging a battery that has little charge left, the charge status will fluctuate quite a bit.

My guess is that your "bad" battery isn't accepting a normal charge, the charge status doesn't really change, and, therefore, the script believes your CAP is not plugged in and the battery is dead so it shuts it down.

This may be an opportunity for us to refine the script for your scenario.

If your numbers are from a v2 with a good battery, maybe v2s charging is "better" than v1?



_____________________________

**Comment by needlestack** [comment]
Ok, so my original comment's suggested fix doesn't make *any* sense, as "0" is greater than both -200 and -20. So ignore that completely :) We still have the problem though, of the unit shutting down. It just turns out that is triggered by the chargeStatus on my dead battery occasionally dropping to -255 from time to time, at which point batteryWatcher notices that the chargeLevel is also < 3 (the bad battery reports 2) and then it shuts the unit down.

Indeed - my latest "good" numbers are from a v2, although I chose -20 as the cutoff for "charging" when I did the battery indicator in contentshell, and that was based on testing with a v1. I imagine there's some variability across units. The analog world is always fickle :)

Whatever the case, the existing setup does seem to render units with dead batteries unusable, so we need to think of a solution to that. As units age, bad batteries will become more and more common :/

**Comment by j-schwartz** [comment]
Hi guys - worrisome thread here, I'm not sure I fully understand.  I can tell you I have been working with Gemtek because I have 7 devices with 'bad batteries' on batteries that either don't hold a charge or shutdown soon after booting up.  Is it possible this is something we're doing to the battery?

**Comment by j-schwartz** [comment]
![image](https://user-images.githubusercontent.com/9270388/27563533-230923e0-5a87-11e7-81f2-75b8d079ac41.png)

**Comment by needlestack** [comment]
No - we're definitely not doing anything to damage the battery. All we're doing is checking the level/status the same way the built-in Intel admin portal does.

The issue is our batteryWatcher that shuts the system down safely when the level is low (<2%) and it's not plugged in: if the battery is bad it always looks like it's not plugged in, and it always looks like it's <2%, so even though the system is plugged in and running, batteryWatcher shuts it down.

It's not clear we can really identify when a unit has a bad battery vs. when it's unplugged and low on power -- they may look about the same. If we can't, we may be better off removing the batteryWatcher...

**Comment by spatiald** [comment]
That raises a good question. Especially in the field locations where we put these...it wouldn't be uncommon to replace the battery. It's also easy to access...

Is there a way to purchase just batteries from Gemtek that we can provide as a replacement?

As for the script, I'll see if there is a way to detect a bad battery and not shutdown. I believe there is as I can run the cap without a battery...no issues and no shutdown.

________________________________

**Comment by j-schwartz** [comment]
We've had a nightmare of a time shipping batteries packaged in devices (in the CAP).  Shipping batteries without a CAP seems like an incredibly difficult situation to manage within the law.  Not saying we couldn't do it, but it's not something I'm planning on trying.

**Comment by hackersforcharity** [comment]
I have purchased battery (up to 10 26AH at a time) from China with fast
shipping.

It's weird you are having issues with shipping in the CAP. It's like any
other electronic device (laptop, phone).

Maybe we can buy from another manufacturer...same battery and cable. I can
check my source if you like.


On Jun 26, 2017, at 18:59, Jeremy Schwartz <notifications@github.com> wrote:

We've had a nightmare of a time shipping batteries packaged in devices (in
the CAP). Shipping batteries without a CAP seems like an incredibly
difficult situation to manage within the law. Not saying we couldn't do it,
but it's not something I'm planning on trying.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/75#issuecomment-311205266>,
or mute the thread

**Comment by spatiald** [comment]
I don't think so - the immediate shutdown should only occur if the battery is below 3% and the unit is not plugged in. The script just sends the shutdown after the the script starts and checks the log files for battery status.

There is nothing in our script that affects the battery. It only checks log files for the battery statuses.

Most likely you are seeing bad batteries from the source. It happens and you've distributed a fairly large quantity of CAPs.


________________________________

**Comment by spatiald** [comment]
Lines 1-5 seem to be the only ones related to bad batteries

6-7 appear to be bad power supply or board

_____________________________

**Comment by spatiald** [comment]
Update posted to [cap-rachel-configure.sh v2.1.12](https://github.com/rachelproject/rachelplus/blob/master/cap-rachel-configure.sh)

Lots of tweaks:
- installed as a service (fixed running at first install issue)
- compatible with upstart (14.04 and below) and future proof systemd (16.04)
- checks for possible bad battery and stops monitoring if situation found (battery connected, charge level is below 95%, and chargeStatus is within a specific range (above -275 and below 400) - this situation should not occur with a working battery
- logs events to /var/log/rachel/battery.log
- update or install with cap-rachel-configure.sh, option 8 (advanced), option 2 (install-battery-watcher)

Believe this issue is resolved.

**Comment by needlestack** [comment]
Tested on my unit with bad battery - works perfectly. Cool!

I didn't know about `battery_connected_status` and `batteryLastChargeLevel` -- is there documentation on any of that stuff?

Just wondering if the batteryLastChargeLevel cutoff of 95% is high enough -- my good unit currently reports 95 (a CAP2, less than six months old), so it seems like there isn't much wiggle room there. I imagine older batteries might report lower numbers under normal operation?

**Comment by spatiald** [comment]
I think it is high enough. The CAP will attempt to charge to 100%. It may not always get there but in its attempt it will keep the charge status between 950 and 1000. As it nears 100%, it slowly brings the charge rate down. But even so, it won't even lower the charge status to 400 until around 99%.

At 95%, the charge status should still be close to the 980 level. If, at that point, the charge status is below 400, that is indicative of a bad power supply or battery and the battery monitor should be killed. It is the combination of those things that matters not each one independently.

To minimize false positives, it keeps a lot of how many times it met the requirement and only kills the monitor if the counts exceeds 3. Sometimes the charge status will drop to 255 (as you noticed) but it normally only occurs for 1-2 secs.

**Comment by needlestack** [comment]
Whoops, I actually meant "low enough" -- but I get your explanation :)
